# This action triggers the build hook
    name: Build

    # Controls when the workflow will run
    on:
     schedule:
     # Runs every 10 minutes
     - cron: "*/10 * * * *"
     # Allows you to run this workflow manually from the Actions tab
     workflow_dispatch:
     
    # The workflow to run
    jobs:
     build:
        runs-on: ubuntu-latest
            steps:
     # Runs a request to the build hook
            - name: Build hook request
            run: curl -X POST ${{ secrets.DEPLOY_HOOK }}

