# This action triggers the build hook
    name: Deployer

    # Controls when the workflow will run
    on:
      schedule:
      # Runs every 60 minutes
      - cron: "*/60 * * * *"
      # Allows you to run this workflow manually from the Actions tab
     
    # The workflow to run
    jobs:
     build:
        runs-on: ubuntu-latest
        steps:
     # Runs a request to the build hook
          - name: Deploy hook request
            run: curl -X POST ${{ secrets.DEPLOY_HOOK }}

